[package]
name = "evm-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
env_logger = "0.10.0"
ethnum = "1.3.2"
hex = "0.4.3"
lazy_static = "1.4.0"
sha3 = "0.10.8"
